---
name: Release
on: # yamllint disable-line rule:truthy
    push:
jobs:
    release:
        # permissions:
        #     contents: write
        #     issues: write
        #     pull-requests: write
        #     id-token: write
        name: Release
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  persist-credentials: false

            - name: Import Secrets
              id: import-secrets
              uses: hashicorp/vault-action@v3
              with:
                  url: ${{ secrets.VAULT_ADDR }}
                  caCertificate: ${{ secrets.ROOT_CA_CERTIFICATE_CONTENT_BASE64 }}
                  clientKey: ${{ secrets.VAULT_CLIENT_PRIVATE_KEY_CONTENT_BASE64 }}
                  clientCertificate: ${{ secrets.VAULT_CLIENT_CERTIFICATE_CONTENT_BASE64 }}
                  method: approle
                  roleId: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
                  secretId: ${{ secrets.VAULT_APPROLE_SECRET_ID }}
                  exportEnv: false
                  exportToken: false
                  secrets: >-
                      vault-secrets/data/vault_secrets/github_details/github_bot GH_BOT_GPG_PASSPHRASE ;

                      vault-secrets/data/vault_secrets/github_details/github_bot GH_BOT_GPG_PRIVATE_KEY ;

                      vault-secrets/data/vault_secrets/github_details/github_bot GH_BOT_API_TOKEN ;

            - name: Import GPG key
              id: import-gpg
              uses: crazy-max/ghaction-import-gpg@v6
              with:
                  gpg_private_key: ${{ steps.import-secrets.outputs.GH_BOT_GPG_PRIVATE_KEY }}
                  passphrase: ${{ steps.import-secrets.outputs.GH_BOT_GPG_PASSPHRASE }}
                  git_user_signingkey: true
                  git_commit_gpgsign: true
                  trust_level: 5

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version: "1.21"
                  check-latest: true
                  cache-dependency-path: go.sum

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*
                  cache: npm
                  cache-dependency-path: .github/files/package-lock.json

            - name: Install node dependencies
              run: |+
                  set -ex
                  npm i semantic-release@24.0.0 \
                    @semantic-release/commit-analyzer@13.0.0 \
                    @semantic-release/release-notes-generator@14.0.0 \
                    @semantic-release/changelog@6.0.3 \
                    @semantic-release/exec@6.0.3 \
                    @semantic-release/git@10.0.1 -D

            - name: Release
              run: |
                  set -ex
                  git config --global user.email "${{ steps.import-gpg.outputs.email }}"
                  git config --global user.name "${{ steps.import-gpg.outputs.name }}"
                  npx semantic-release@24.0.0 --extends ./.github/files/release.config.mjs
              env:
                  GITHUB_TOKEN: ${{ steps.import-secrets.outputs.GH_BOT_API_TOKEN }}
                  GIT_AUTHOR_NAME: ${{ steps.import-gpg.outputs.name }}
                  GIT_AUTHOR_EMAIL: ${{ steps.import-gpg.outputs.email }}
                  GIT_COMMITTER_NAME: ${{ steps.import-gpg.outputs.name }}
                  GIT_COMMITTER_EMAIL: ${{ steps.import-gpg.outputs.email }}
