---
name: Release
on: # yamllint disable-line rule:truthy
    push:
jobs:
    release:
        # permissions:
        #     contents: write
        #     issues: write
        #     pull-requests: write
        #     id-token: write
        name: Release
        runs-on: ubuntu-latest
        container: redhat/ubi8
        steps:
            - name: Install gpg and git and set safe directory
              run: |+
                  set -ex
                  dnf install -y gnupg2 git
                  git config --global --add safe.directory "$(pwd)"

            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  persist-credentials: false
                  path: ${{ github.workspace }}
                  set-safe-directory: true

            - name: Import GPG key
              id: import-gpg
              uses: crazy-max/ghaction-import-gpg@v6
              with:
                  gpg_private_key: ${{ secrets.GH_BOT_GPG_PRIVATE_KEY }}
                  passphrase: ${{ secrets.GH_BOT_GPG_PASSPHRASE }}
                  git_user_signingkey: true
                  git_commit_gpgsign: true
                  trust_level: 5

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version: "1.21"
                  cache: false

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*
                  cache: npm
                  cache-dependency-path: .github/files/package-lock.json

            - name: Install node dependencies
              run: |+
                  set -ex
                  npm i semantic-release@24.0.0 \
                    @semantic-release/commit-analyzer@13.0.0 \
                    @semantic-release/release-notes-generator@14.0.0 \
                    @semantic-release/changelog@6.0.3 \
                    @semantic-release/exec@6.0.3 \
                    @semantic-release/git@10.0.1 -D

            - name: Release
              run: |
                  set -ex
                  git config --global user.email "${{ steps.import-gpg.outputs.email }}"
                  git config --global user.name "${{ steps.import-gpg.outputs.name }}"
                  npx semantic-release@24.0.0 --extends ./.github/files/release.config.mjs
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_BOT_API_TOKEN }}
                  GIT_AUTHOR_NAME: ${{ steps.import-gpg.outputs.name }}
                  GIT_AUTHOR_EMAIL: ${{ steps.import-gpg.outputs.email }}
                  GIT_COMMITTER_NAME: ${{ steps.import-gpg.outputs.name }}
                  GIT_COMMITTER_EMAIL: ${{ steps.import-gpg.outputs.email }}
